spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tax_application?createDatabaseIfNotExist=true
    username: root
    password: Sonu123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
server:
  port: 8082
okta:
  oauth2:
    issuer: https://dev-99845851.okta.com/oauth2/default
    client-id: 0oal0gwc5fh33gBf25d7
    client-secret: azSExDGSMXfk5Nr0cXo_g2jeCqNSMauyIllQUUJRwK_oJp5ykBSDiuj1LXnMscO4